#!/bin/bash
#Menu
clear
echo -e "* menu            : Menampilkan daftar perintah"
echo -e "* usernew         : Membuat akun SSH & OpenVPN"
echo -e "* trial           : Membuat akun trial"
echo -e "* hapus           : Menghapus akun SSH & OpenVPN"
echo -e "* cek             : Cek user login"
echo -e "* cekconfig       : Cek config yang tersedia"
echo -e "* member          : Daftar member SSH & OpenVPN"
echo -e "* crot69          : Restart service Openssh,Dropbear"
echo -e "                    Stunnel,OpenVPN dan Shadowsocks"
echo -e "* reboot          : Reboot VPS"
echo -e "* speedtest       : Speedtest VPS"
echo -e "* vpn-beta        : Install OpenVPN Server"
echo -e "* shadowsl        : Install Shadowsocks Server"
echo -e "* monitorvpn      : Install OpenVPN-Monitor"
echo -e "* shadowsocks-all : Install Shadowsocks Lengkap"
echo -e "* info            : Menampilkan informasi sistem"
echo -e "* about           : Info script auto install"
echo -e "* exit            : Keluar dari Putty/Connecbot/"
echo -e "                  : JuiceSSH"
echo -e ""
